//
//  File.swift
//  
//
//  Created by Jose Moran on 30/5/24.
//

import Foundation
import Alamofire

class ApiConfig {
  static var baseUrl: String  {
   return LukaStripeSdk.instance.config.env == .live ?
    "https://lukaapi.payco.net.ve/api/v1" : "https://bspaycoapi-qa.payco.net.ve/api/v1"
  }
}


func provideCertificate() -> SecCertificate {
  
//  let bundle = Bundle.main
//  
//  guard let certificatePath = bundle.url(forResource: "payco2024", withExtension: "cer") else {
//      fatalError("Couldn't find certificate file")
//  }
  
  let certString = "MMOHBsOoMMOHBXfigKADAgECAgkAwqszSHlnUMucw7kwCgYJKsOcSMOcy5wKAQELBQAww4XCpTELMAkGA1UEBhMCVVMxEDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoTEUdvRGFkZHkuY29tLCBJbmMuMS0wKwYDVQQLEyRodHRwOi8vY2VydHMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS8xMzAxBgNVBAMTKkdvIERhZGR5IFNlY3VyZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgLSBHMjAeFwoyMzA2MjExODIwNDFaFwoyNDA3MjIxODIwNDFaMBkxFzAVBgNVBAMMDioucGF5Y28ubmV0LnZlMMOHASIwCgYJKsOcSMOcy5wKAQEBBQADw4cBDwAww4cBCgLDhwEBAOKAmcKxw5UKOcKiEsWTw7bDoCEKKD3LmMOIcuKJoM6pW2TDrBHDoMO1xZPLm+KAlApuSUlYJsKiw4nCoMuG4oCwwqXDowZqZHYqw6jDuVlswr8/4oirEjrCrOKAlBc6PynDu8OvwrvDiMObw4IC4oC6UVpVMOKAsDPEsRVUG8K44omIFOKAnCpzNS5Lw64iy4figJ06I8OFbR3DmsKiw4zil4rCoG8yw40cEBbDkcOZclZLw6DiiaDiiaXDssKly5rigLDCpe+sgcKjQeKAueKInsK4GQoyy5otJwrCseKJiMOJRTrigqzFk8OzX1figLkRw5wy76yBdR99w4rCqcOrZTPCt8WTwrAnw44Tw4dMaG/LmEPCtA4Vy5scw5zCojTDusOR4oSiQWrigKbCoDbDk8OoTUHDp8O3OD3CqQwlw4JpPAXDheKApj/igKJrYMO276O/w5kjw4Z2M0VGQ8K0AcOGJ2UYH13iiJpBw6RvDD3DjsOmTnPDtEcZw5M1f8O5WTzDp0VRJyHCpQs+IcOYxZJ7cQIDAQABwqPDhwM8MMOHAzgwDAYDVR0TAQHLhwQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA4GA1UdDwEBy4cEBAMCBeKAoDA4BgNVHR8EMTAvMC3igKAr4oCgKcOcJ2h0dHA6Ly9jcmwuZ29kYWRkeS5jb20vZ2RpZzJzMS02MzQyLmNybDBdBgNVHSAEVjBUMEgGC2DDnEgBw5zLnW0BBxcBMDkwNwYIKwYBBQUHAgEWK2h0dHA6Ly9jZXJ0aWZpY2F0ZXMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS8wCAYGZ8OFDAECATB2BggrBgEFBQcBAQRqMGgwJAYIKwYBBQUHMAHDnBhodHRwOi8vb2NzcC5nb2RhZGR5LmNvbS8wQAYIKwYBBQUHMALDnDRodHRwOi8vY2VydGlmaWNhdGVzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvZ2RpZzIuY3J0MB8GA1UdIwQYMBbDhBRAwqzOqSfDqcODNMOJMMKiM+KXisuabOKJpe+jv8KlLMOExZIwJwYDVR0RBCAwHsOHDioucGF5Y28ubmV0LnZlw4cMcGF5Y28ubmV0LnZlMB0GA1UdDgQWBBTiiaTDqUw7OsOyOBY8Y8OEy4dRz4BJ4oCeceKAncKnw6kww4cBfQYKKwYBBAHDt3kCBAIEw4cBbQTDhwFpAWcAdgDDk8OV4oCTZOKAmeKCrBrFkuKJiFziiJHDucKlw5UTwqIyw6FGfMK6w4/vrIHiiJpRSFlGcR/CtcO1AAABw6DvrIIvy4YyAAAEAwBHMEUCIQDDueKXisOSwrvCoSHDqsOcw6HCuyg54oiPCeKIj+KAoUFe4oKs4oCZO8uYbMOZdcOiaDTDseKAnsKiwrYCICAJw7TigJzigKbDgQgIwqDDlsOpXMOWwqAuwrsuRcOrw5vigYTFuOKAsOKAuQYB4peKXmYMw78pAHUASOKInuKAnmvigYTCtkc0D8OCagLLmcO5MMOOHFIBw4BW4oC6LMOFxbjCqsO4wrQ5w7/DkXMAAAHDoO+sgi/LnAIAAAQDAEYwRAIgSgPCoxlvTwoIYuKAnuKAoVbigJjigJxjEm3CpcO1w7TigLArHULDoQRAfjU3WV4CIHcYH2PDqwZjM8OUdcKqw6dgw6JTQs6pcnsqR+KIggpSR1rLnMucEuKJpOKAoXwAdgDigYTiiILDuGs/wrXiiIIiw7zDtcKswqpca8OLcMOrcWzCqlHDkcOWNM6pwqc9MEjil4rLmsK0AAABw6DvrIIvy5xmAAAEAwBHMEUCIHYEw5PigJnCtzFUwqNiw5XDmlgwxZJHJsK3w4fDjuKIhsW4aDI2FMORw4xwHeKIglvDuQIhAMuZwqJFK8WS4oCiw4HFuEtOQRQfHsOLw5QBCuKAuW9vw4jDtcO6UAE1djdb4oCcwqgwCgYJKsOcSMOcy5wKAQELBQADw4cBAQB+w6wvw6TigLDiiJ4CwqlnzqnDreKAmC3DrTrCqeKEou+jv3TDlcOT4oCYKsKpwrF7WhBZy5zDk8K6w7HCr3oyUcK/4oKsSeKXisOLI3Z0wrrDh30kXEPDsmEuZcO8w7vDmcOSREYSK86pEnUPw7XDt++sgTAXaOKJiOKIq8Ks4oCcw7oMCmBPZMO5w7QFSeKXig4+cAJbw44zeDg4bD/CrgcWNcK2Nw7DpmLigJrDieKIhsKsSxt7cljiiILEsRtfC++sgSpHw4h+MiDCqzrigJnDu+KJpGFyV8Ouwr/igJxWwrVqwqhVfMKixpJsKuKIhijDj1figqw+VsOve+KIhgFtIuKAncOFKSvCocOyw7VHwqjDnMOpLl3Ds+KIngDDocOx4peKL03DicK14oiGw6HDrcOcw44I4omIDsOc4oCZw4NYwqzLmxoab8+AFOKInl4gw6tOHHt8wqIiSeKJoGvLhsSxw5rigqzDmUMxFiNx76yCZgvigKbDksON4oCaYMO/w5TDuMOTw5R3XOKAnuKInsOPw4XigJTil4rPgMOuw4gCy5jDoQ=="
  
  guard let data = Data(base64Encoded: certString) else {
    fatalError("Couldn't find certificate file")
  }

  let certificateData = NSData(data: data)
  return SecCertificateCreateWithData(nil, certificateData)!
 
}

func provideSessionManager() -> Session {
  let certificateData = provideCertificate()
  let serverTrustPolicies: [String: ServerTrustEvaluating] = [
          "lukaapi.payco.net.ve": PinnedCertificatesTrustEvaluator(certificates: [certificateData]),
          "bspaycoapi-qa.payco.net.ve": PinnedCertificatesTrustEvaluator(certificates: [certificateData]),
      ]
  
  let sessionManager = Session(
    configuration: .default,
    serverTrustManager: ServerTrustManager(evaluators: serverTrustPolicies)
  )
  
  return sessionManager
}
